# frozen_string_literal: true
gem "rake"
source "https://rubygems.org"
gem "sinatra" , "2.2.2"
gem "puma" , "5.6.5"
gem "ostruct"
gem "sqlite3"
gem "bcrypt"
gem "sinatra-activerecord"
gem "activerecord"
gem "rackup"
# gem "rails"
